### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by FilipeRamalho** [GoldenDeveloper79/TheBasics#2]
I looked over your code and noticed that you dont have vault support
In Bukkit and Spigot its very important to have have vault support for scoreboard plugins or selling plugins

Could you add that 
If you add that i think personally that TheBasics is the best plugin minecraft as ever seen because it combines permissionex with fe and essentials

**Comment by FilipeRamalho** [comment]
And in the future you could also add a scoreboad function

**Comment by GoldenDeveloper79** [comment]
I can only ask Vault to add my plugin.

**Comment by FilipeRamalho** [comment]
You can by yourself add support 
Look at this plugin the VaultHandler class
https://github.com/niccholaspage/Fe/blob/master/src/org/melonbrew/fe/VaultHandler.java

**Comment by GoldenDeveloper79** [comment]
Oh I see, I will look into this.
